-- SUPABASE BEST PRACTICES & SCHEMA OPTIMIZATION
-- Generated by 'supabase-postgres-best-practices' skill

-- 1. ROW LEVEL SECURITY (RLS)
-- Enable RLS on all tables to ensure secure access.

ALTER TABLE IF EXISTS public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.trips ENABLE ROW LEVEL SECURITY;

-- Policies for 'profiles'
CREATE POLICY "Public profiles are viewable by everyone" 
ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can update own profile" 
ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Policies for content (albums, memories, trips, quotes)
-- Readable by authenticated users
CREATE POLICY "Content is viewable by authenticated users" 
ON public.albums FOR SELECT TO authenticated USING (true);

CREATE POLICY "Content is viewable by authenticated users" 
ON public.memories FOR SELECT TO authenticated USING (true);

CREATE POLICY "Content is viewable by authenticated users" 
ON public.trips FOR SELECT TO authenticated USING (true);

CREATE POLICY "Content is viewable by authenticated users" 
ON public.quotes FOR SELECT TO authenticated USING (true);

-- Writable only by Admins
-- (Assumes a function or claim exists, or we check profile role)
-- Simplest approach using a subquery (perf warning: check cost) or better, a custom claim.
-- For now, using query based on profiles table.
CREATE POLICY "Admins can insert/update/delete content" 
ON public.albums FOR ALL USING (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

CREATE POLICY "Admins can insert/update/delete content" 
ON public.memories FOR ALL USING (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

CREATE POLICY "Admins can insert/update/delete content" 
ON public.trips FOR ALL USING (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- 2. INDEX OPTIMIZATIONS
-- Add indexes to foreign keys and commonly ordered/filtered columns.

-- Index for Memories by Album (Foreign Key)
CREATE INDEX IF NOT EXISTS idx_memories_album_id ON public.memories(album_id);

-- Index for ordering Memories by date
CREATE INDEX IF NOT EXISTS idx_memories_date ON public.memories(date DESC);

-- Index for ordering Trips by date
CREATE INDEX IF NOT EXISTS idx_trips_start_date ON public.trips(start_date ASC);

-- Index for ordering Albums
CREATE INDEX IF NOT EXISTS idx_albums_created_at ON public.albums(created_at DESC);

-- 3. STORAGE POLICIES (Reference)
-- Ensure 'memories' bucket is public for viewing but restricted for uploading.
-- insert: auth.role() = 'authenticated' (or check admin)
-- select: true

-- 4. RPC FOR RANDOM QUOTE (Optimization)
-- Avoids fetching all rows to client.
CREATE OR REPLACE FUNCTION get_random_quote()
RETURNS SETOF quotes AS $$
BEGIN
  RETURN QUERY SELECT * FROM quotes ORDER BY random() LIMIT 1;
END;
$$ LANGUAGE plpgsql;
